export const FETCH_BY_SEARCH_REQUEST = 'FETCH_BY_SEARCH_REQUEST';
export const FETCH_BY_SEARCH_SUCCESS = 'FETCH_BY_SEARCH_SUCCESS';
export const FETCH_BY_SEARCH_ERROR = 'FETCH_BY_SEARCH_ERROR';

export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const DELETE_FROM_FAVOURITE = 'DELETE_FROM_FAVOURITE';

export const FETCH_FAVOURITE = 'FETCH_FAVOURITE';

export const SET_FILTER = "SET_FILTER";
